apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: file-integrity-daemon
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: file-integrity-daemon
subjects:
- kind: ServiceAccount
  name: file-integrity-daemon
