kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: file-integrity-daemon
subjects:
  - kind: ServiceAccount
    name: file-integrity-daemon
roleRef:
  kind: Role
  name: file-integrity-daemon
  apiGroup: rbac.authorization.k8s.io
