apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: file-integrity-operator-metrics
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: file-integrity-operator-metrics
subjects:
  - kind: ServiceAccount
    name: prometheus-k8s
    namespace: openshift-monitoring