kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: file-integrity-operator
subjects:
  - kind: ServiceAccount
    name: file-integrity-operator
roleRef:
  kind: Role
  name: file-integrity-operator
  apiGroup: rbac.authorization.k8s.io